### ISSUE TITLE
Hyperkube deprecation

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pke#112]
Hyperkube was deprecated and there are no official images shipped as of 1.19

We don't seem to use it since 1.18, but it's worth noting as in the `v1beta3` it will be removed.

Some references:

- kubernetes/kubeadm#1889
- kubernetes/kubernetes#84662
- kubernetes/kubernetes#85094
- /kubernetes/kubernetes#85137
- kubernetes/kubernetes#81760

**Comment by pbalogh-sa** [comment]
Hypercube deprecated: #144
