### ISSUE TITLE
Upgrade containerd

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pke#120]

**Comment by gecube** [comment]
What is the current version of containerd in PKE?

I made some experiment with gVisor runtime and I was forced to install the latest containerd manually (v1.4.3 at this moment).

**Comment by sagikazarmark** [comment]
Currently we install 1.3.3.

PRs are welcome, but we need to run an extensive set of tests to actually release an upgrade like this, so it might take some time.

**Comment by pbalogh-sa** [comment]
Now the latest stable containerd is used (1.5.9)
