### ISSUE TITLE
Consider embedding static assets 

### ISSUE THREAD

**Issue by csreegn** [banzaicloud/pke#31]
Improvement idea (easier maintenance):

Looking at the code there's a bunch of inlined text, like this:
https://github.com/banzaicloud/pke/blob/master/cmd/pke/app/phases/kubeadm/node/kubeadm.go#L112

For easier maintenance you could consider embedding static assets instead of defining them inline as sting:
https://github.com/avelino/awesome-go#resource-embedding

**Comment by Ecsy** [comment]
It is not off the table. I have used packr v2 before, but it had some issues with multi command repositories. We need to evaluate options which best fits text/template usage.
